development: &default
  es_bin: '../elasticsearch-6.6.2/bin/elasticsearch'
  host: 'http://localhost:9200'
  port: '9200'
production:
  es_bin: '../elasticsearch-6.6.2/bin/elasticsearch'
  host: 'http://localhost:9400'
  port: '9400'
